"""
Данные курса C# Study — сюжетная версия (plotCourseData).
Экспортируется как PLOT_COURSE для использования в seed.py.
"""

PLOT_COURSE = [
    # ===========================================================================
    # ТЕМА 1 — СКРЫТАЯ ДЕРЕВНЯ (Переменные, типы, ввод-вывод). Отсылка: Наруто.
    # ===========================================================================
    {
        "id": "topic-1",
        "order": 1,
        "title": "Скрытая Деревня",
        "storyPage": {
            "id": "t1-story-intro",
            "title": "Пробуждение",
            "blocks": [
                {"type": "title", "content": "Скрытая Деревня"},
                {"type": "text",  "content": "# открывает глаза. Деревянный потолок, запах хвои, тишина — слишком долгая для деревни ниндзя."},
                {"type": "text",  "content": "Над ним склоняется Старейшина. Спокойно, без удивления: «Ты вернулся. Год тебя не было.»"},
                {"type": "text",  "content": "Год. Принцесса C похищена. Столицу удерживает кто-то по имени Null. # не помнит даже своего имени."},
                {"type": "subtitle", "content": "Что от тебя нужно"},
                {"type": "text",  "content": "Деревня увядает: Null разболтал секреты, свитки утеряны, жители уходят. Помоги Старейшине восстановить восемь свитков знаний — и деревня снова начнёт дышать."},
            ],
        },
        "theoryPages": [
            {
                "id": "t1-l1-var-concept",
                "title": "Что такое переменная",
                "blocks": [
                    {"type": "title", "content": "Переменная"},
                    {"type": "text",  "content": "Переменная — это именованная ячейка памяти. Старейшина называет это «свитком»: у каждого свитка есть подпись (имя) и содержимое (значение)."},
                    {"type": "code",  "content": "int age = 18;"},
                    {"type": "text",  "content": "Слева тип (int — целое число), потом имя (age), потом значение через знак =."},
                ],
            },
            {
                "id": "t1-l2-types",
                "title": "Типы данных и объявление",
                "blocks": [
                    {"type": "title", "content": "Базовые типы"},
                    {"type": "text",  "content": "У каждого свитка есть «природа чакры» — тип данных. Он говорит, что именно лежит внутри."},
                    {"type": "code",  "content": "int count = 10;       // целые числа\ndouble price = 9.99;  // дробные числа\nbool isReady = true;  // логическое (true/false)\nchar letter = 'A';    // один символ"},
                    {"type": "text",  "content": "Тип нужно подбирать под задачу. Хранить деньги в int — потеряешь копейки."},
                ],
            },
            {
                "id": "t1-l3-strings",
                "title": "Строки",
                "blocks": [
                    {"type": "title", "content": "Строки"},
                    {"type": "text",  "content": "Строка (string) — это последовательность символов в двойных кавычках."},
                    {"type": "code",  "content": 'string name = "Отуран";\nstring hello1 = "Привет, " + name;     // конкатенация\nstring hello2 = $"Привет, {name}";    // интерполяция\nchar first = name[0];                 // обращение по индексу'},
                    {"type": "text",  "content": "Спецсимволы экранируются обратной чертой: \\n — перенос строки, \\\" — кавычка внутри строки."},
                ],
            },
            {
                "id": "t1-l4-const",
                "title": "Константы",
                "blocks": [
                    {"type": "title", "content": "Константы"},
                    {"type": "text",  "content": "Если значение никогда не должно меняться — объяви его как const. Это «запечатанный свиток»."},
                    {"type": "code",  "content": 'const double Pi = 3.14159;\nconst string AppName = "C# Study";'},
                    {"type": "text",  "content": "Попытка переписать const — ошибка компиляции. Никаких исключений в рантайме, всё ловится сразу."},
                ],
            },
            {
                "id": "t1-l5-io",
                "title": "Консольный ввод и вывод",
                "blocks": [
                    {"type": "title", "content": "Console.WriteLine и Console.ReadLine"},
                    {"type": "text",  "content": "Чтобы что-то вывести — WriteLine. Чтобы прочитать ввод пользователя — ReadLine."},
                    {"type": "code",  "content": 'Console.WriteLine("Как тебя зовут?");\nstring name = Console.ReadLine();\nConsole.WriteLine($"Здравствуй, {name}");'},
                    {"type": "text",  "content": "ReadLine всегда возвращает string. Если нужно число — придётся преобразовать."},
                ],
            },
            {
                "id": "t1-l6-arithmetic",
                "title": "Арифметика",
                "blocks": [
                    {"type": "title", "content": "Арифметические операции"},
                    {"type": "code",  "content": "int a = 7;\nint b = 2;\n\nConsole.WriteLine(a + b);  // 9\nConsole.WriteLine(a - b);  // 5\nConsole.WriteLine(a * b);  // 14\nConsole.WriteLine(a / b);  // 3 — целочисленное деление!\nConsole.WriteLine(a % b);  // 1 — остаток"},
                    {"type": "text",  "content": "Когда оба операнда — целые, деление тоже целое: 7 / 2 = 3, дробная часть отброшена. Хочешь дробь — хотя бы один операнд должен быть double."},
                ],
            },
            {
                "id": "t1-l7-cast",
                "title": "Приведение типов",
                "blocks": [
                    {"type": "title", "content": "Преобразование типов"},
                    {"type": "text",  "content": "Неявное приведение: компилятор сам, если безопасно."},
                    {"type": "code",  "content": "int a = 10;\ndouble b = a;     // OK, int спокойно становится double"},
                    {"type": "text",  "content": "Явное приведение: ты сам пишешь тип в скобках. Может терять данные."},
                    {"type": "code",  "content": "double x = 9.7;\nint y = (int)x;   // 9 — дробная часть отбрасывается"},
                ],
            },
        ],
        "tasks": [
            {
                "id": "t1-task-1", "type": "single-choice",
                "title": "Старейшина: что такое свиток",
                "npcText": "Старейшина смотрит внимательно. «Прежде чем доверить тебе свитки — скажи. Что такое переменная?»",
                "question": "Что такое переменная?",
                "options": ["именованная ячейка памяти", "команда вывода", "название функции", "название типа"],
                "correctIndex": 0,
                "rewardXp": 10,
            },
            {
                "id": "t1-task-2", "type": "match-pairs",
                "title": "Свитки без подписей",
                "npcText": "«Null стёр подписи. Расставь обратно — какое значение какой природы.»",
                "pairs": [
                    {"left": "42",   "right": "int"},
                    {"left": "3.14", "right": "double"},
                    {"left": "true", "right": "bool"},
                    {"left": "'A'",  "right": "char"},
                ],
                "rewardXp": 15,
            },
            {
                "id": "t1-task-3", "type": "fill-in-blank",
                "title": "Знакомство с Отураном",
                "npcText": "Подбегает молодой ниндзя: «Я стану великим! Сделай первую запись с моим именем — и потом ты будешь первым, кто меня знал!»",
                "codeTemplate": '___ name = "Отуран";',
                "blank": "string",
                "rewardXp": 15,
            },
            {
                "id": "t1-task-4", "type": "single-choice",
                "title": "Старейшина: правила именования",
                "npcText": "«Свиток с плохой подписью никто не сможет найти. Какое имя подходит?»",
                "question": "Какое имя подходит для переменной?",
                "options": ["123name", "myName", "name!", "for"],
                "correctIndex": 1,
                "rewardXp": 10,
            },
            {
                "id": "t1-task-5", "type": "code-order",
                "title": "Зачитать заклинание",
                "npcText": "«Заклинание срабатывает только когда его произнесут вслух. Собери код.»",
                "description": "Расставь строки: сначала объяви свиток с заклинанием, потом выведи его в консоль.",
                "lines": [
                    'string spell = "Огненный шар!";',
                    "Console.WriteLine(spell);",
                ],
                "correctOrder": [0, 1],
                "rewardXp": 15,
            },
            {
                "id": "t1-task-6", "type": "fill-in-blank",
                "title": "Старейшина шепчет ответ",
                "npcText": "«Запиши то, что я скажу.» Старейшина шепчет — нужно прочитать его слова в переменную.",
                "codeTemplate": "string answer = Console.___();",
                "blank": "ReadLine",
                "rewardXp": 15,
            },
            {
                "id": "t1-task-7", "type": "fill-in-blank",
                "title": "Перевод чакры",
                "npcText": "«Чакра воды (double) должна стать чакрой земли (int). Явно. Иначе компилятор не пропустит.»",
                "codeTemplate": "double damage = 9.7;\nint hit = ___(damage);",
                "blank": "(int)",
                "rewardXp": 15,
            },
            {
                "id": "t1-task-8", "type": "single-choice",
                "title": "Запечатанный свиток",
                "npcText": "Отуран в стороне сосредоточенно скребёт свиток. «Я тут хочу переписать… а оно не даётся!»",
                "question": "Что произойдёт, если попытаться изменить переменную, объявленную как const?",
                "options": [
                    "значение изменится",
                    "компилятор выдаст ошибку",
                    "программа упадёт при запуске",
                    "ничего не произойдёт",
                ],
                "correctIndex": 1,
                "rewardXp": 10,
            },
            {
                "id": "t1-task-9", "type": "single-choice",
                "title": "«5» + «3»",
                "npcText": "Торговец возмущён: «Записал цену и налог, а свиток показывает какую-то ерунду!»",
                "question": 'Что выведет код Console.WriteLine("5" + "3"); ?',
                "options": ["8", '"53"', "35", "ошибка компиляции"],
                "correctIndex": 1,
                "rewardXp": 10,
            },
            {
                "id": "t1-task-10", "type": "single-choice",
                "title": "Странный счёт у торговца",
                "npcText": "«Делю 7 на 2 — а получается 3. Половина куда-то делась!»",
                "question": "Что выведет код  int a = 7; int b = 2; Console.WriteLine(a / b);  ?",
                "options": ["3", "3.5", "4", "ошибка"],
                "correctIndex": 0,
                "rewardXp": 10,
            },
            {
                "id": "t1-task-11", "type": "fill-in-blank",
                "title": "Приветствие Отурана",
                "npcText": "«Хочу, чтобы про меня знали! Напиши приветствие — но красиво, с интерполяцией!»",
                "codeTemplate": 'string name = "Отуран";\nConsole.WriteLine($"Привет, ___!");',
                "blank": "{name}",
                "rewardXp": 15,
            },
            {
                "id": "t1-task-12", "type": "find-the-bug",
                "title": "Экзамен у Старейшины",
                "npcText": "«Это программа моего ученика. Один баг. Найди.»",
                "lines": [
                    "const int MaxHealth = 100;",
                    "int currentHealth = 80;",
                    "int healAmount = 25;",
                    "currentHealth = currentHealth + healAmount;",
                    "MaxHealth = currentHealth;",
                    'Console.WriteLine($"Здоровье: {currentHealth}");',
                ],
                "bugLineIndex": 4,
                "explanation": "MaxHealth объявлена как const — её нельзя переприсваивать. Компилятор выдаст ошибку.",
                "rewardXp": 25,
            },
        ],
        "finalAction": {
            "id": "t1-restore-archive",
            "title": "Восстановить архив деревни",
            "cutsceneBlocks": [
                {"type": "title", "content": "Восстановление архива"},
                {"type": "text",  "content": "# раскладывает шесть собранных свитков у ног Старейшины. Тот разворачивает их один за другим, кладёт в нужные ниши."},
                {"type": "text",  "content": "Архив дышит. Где-то на улице слышен смех — впервые за год дети снова бегают по дороге к колодцу."},
                {"type": "text",  "content": "Старейшина поднимает на # глаза. «Я знал твоего отца. И тебя я тоже знаю, рыцарь #.»"},
                {"type": "subtitle", "content": "Возврат памяти"},
                {"type": "text",  "content": "# вспоминает своё имя. Маленький кусочек, но первый."},
            ],
        },
    },

    # ===========================================================================
    # ТЕМА 2 — ЛЕС ГИГАНТСКИХ ДЕРЕВЬЕВ (Условия). Отсылка: Атака Титанов.
    # ===========================================================================
    {
        "id": "topic-2",
        "order": 2,
        "title": "Лес Гигантских Деревьев",
        "storyPage": {
            "id": "t2-story-intro",
            "title": "У Стен",
            "blocks": [
                {"type": "title", "content": "Лес Гигантских Деревьев"},
                {"type": "text",  "content": "Старейшина рассказывал про южные Стены — лес там пробудил тварей, Корпус Разведки несёт потери."},
                {"type": "text",  "content": "# выходит к стенам на рассвете. Дым, ругань командиров, раненые на телегах. На самой высокой точке стоит человек с фляжкой — комендант Пиксис."},
                {"type": "text",  "content": "Пиксис не удивляется. «Ты вовремя. У нас падает боевой дух — а без него стены не удержим. Собери восемь единиц. Я подскажу, где.»"},
            ],
        },
        "theoryPages": [
            {
                "id": "t2-l1-if",
                "title": "Простой if",
                "blocks": [
                    {"type": "title", "content": "Условие if"},
                    {"type": "text",  "content": "if выполняет блок кода только если условие истинно (true)."},
                    {"type": "code",  "content": "bool dangerSpotted = true;\n\nif (dangerSpotted)\n{\n    Console.WriteLine(\"Поднять флаг!\");\n}"},
                    {"type": "text",  "content": "В скобках — условие. В фигурных скобках — что делать, если оно истинно."},
                ],
            },
            {
                "id": "t2-l2-compare",
                "title": "Операторы сравнения",
                "blocks": [
                    {"type": "title", "content": "Сравнение"},
                    {"type": "text",  "content": "Операторы сравнения возвращают bool."},
                    {"type": "code",  "content": "int a = 5;\nint b = 10;\n\nbool less   = a < b;   // true\nbool more   = a > b;   // false\nbool equal  = a == b;  // false\nbool notEq  = a != b;  // true"},
                    {"type": "text",  "content": "Запомни: == — это сравнение. = — это присваивание. Это разные вещи."},
                ],
            },
            {
                "id": "t2-l3-if-else",
                "title": "if / else",
                "blocks": [
                    {"type": "title", "content": "Альтернативная ветка"},
                    {"type": "text",  "content": "else выполняется, если условие if оказалось false."},
                    {"type": "code",  "content": "bool haveRedThread = false;\n\nif (haveRedThread)\n{\n    Console.WriteLine(\"Использую её\");\n}\nelse\n{\n    Console.WriteLine(\"Ищу другую\");\n}"},
                ],
            },
            {
                "id": "t2-l4-else-if",
                "title": "else if (цепочка)",
                "blocks": [
                    {"type": "title", "content": "Несколько веток"},
                    {"type": "text",  "content": "Если веток больше двух — используй цепочку."},
                    {"type": "code",  "content": "int hour = 14;\n\nif (hour < 12)\n{\n    Console.WriteLine(\"Утро\");\n}\nelse if (hour < 18)\n{\n    Console.WriteLine(\"День\");\n}\nelse\n{\n    Console.WriteLine(\"Вечер\");\n}"},
                    {"type": "text",  "content": "Сработает только первая подходящая ветка. Остальные пропустятся."},
                ],
            },
            {
                "id": "t2-l5-ternary",
                "title": "Тернарный оператор",
                "blocks": [
                    {"type": "title", "content": "Тернарный оператор"},
                    {"type": "text",  "content": "Краткая форма if/else, когда нужно просто выбрать одно из двух значений."},
                    {"type": "code",  "content": "int age = 20;\nstring kind = age >= 18 ? \"Взрослый\" : \"Ребёнок\";\nConsole.WriteLine(kind);"},
                    {"type": "text",  "content": "Синтаксис: условие ? значение_если_true : значение_если_false"},
                ],
            },
            {
                "id": "t2-l6-switch",
                "title": "switch",
                "blocks": [
                    {"type": "title", "content": "switch / case"},
                    {"type": "text",  "content": "Когда нужно сравнить одну переменную с множеством конкретных значений — switch удобнее цепочки if/else."},
                    {"type": "code",  "content": "string signal = \"красная\";\n\nswitch (signal)\n{\n    case \"зелёная\":\n        Console.WriteLine(\"Безопасно\");\n        break;\n    case \"жёлтая\":\n        Console.WriteLine(\"Приближается обычный\");\n        break;\n    case \"красная\":\n        Console.WriteLine(\"Аномальный!\");\n        break;\n    default:\n        Console.WriteLine(\"Неизвестный сигнал\");\n        break;\n}"},
                    {"type": "text",  "content": "break обязателен после каждого case — иначе провалится в следующий."},
                ],
            },
        ],
        "tasks": [
            {
                "id": "t2-task-1", "type": "fill-in-blank",
                "title": "Пиксис: тревога на стене",
                "npcText": "«Дозорный заметил движение в лесу. Если опасность — поднять флаг. Допиши.»",
                "codeTemplate": "bool dangerSpotted = true;\n\n___ (dangerSpotted)\n{\n    Console.WriteLine(\"Поднять флаг!\");\n}",
                "blank": "if",
                "rewardXp": 10,
            },
            {
                "id": "t2-task-2", "type": "fill-in-blank",
                "title": "Пиксис: кого первым в укрытие",
                "npcText": "«Двух надо эвакуировать. Младший — первым.»",
                "codeTemplate": "int ageA = 14;\nint ageB = 22;\nif (ageA ___ ageB)\n{\n    Console.WriteLine(\"A идёт в укрытие первым\");\n}",
                "blank": "<",
                "rewardXp": 15,
            },
            {
                "id": "t2-task-3", "type": "single-choice",
                "title": "Подсчёт раненых",
                "npcText": "«Если раненых больше пяти — посылаем второй обоз. Какое условие сработает правильно?»",
                "question": "Какое условие отправит второй обоз, если раненых больше пяти?",
                "options": ["wounded > 5", "wounded < 5", "wounded = 5", "wounded == 5"],
                "correctIndex": 0,
                "rewardXp": 10,
            },
            {
                "id": "t2-task-4", "type": "code-order",
                "title": "Асами: чинит шарф",
                "npcText": "«Порвался шарф. Если есть красная нить — беру её, иначе ищу другую. Помоги собрать код в правильном порядке.»",
                "description": "Расставь строки так, чтобы Асами выбрала нить корректно.",
                "lines": [
                    "bool haveRedThread = true;",
                    "string action;",
                    "if (haveRedThread)",
                    "{",
                    '    action = "Использую её";',
                    "}",
                    "else",
                    "{",
                    '    action = "Ищу другую";',
                    "}",
                    "Console.WriteLine(action);",
                ],
                "correctOrder": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                "rewardXp": 20,
            },
            {
                "id": "t2-task-5", "type": "fill-in-blank",
                "title": "Эрен: вылазка или ждать",
                "npcText": "Эрен горячится: «Если разведка вернулась — идём, иначе ждём. Один оператор — и поехали.»",
                "codeTemplate": 'bool scoutBack = true;\nstring order = scoutBack ___ "Вылазка" : "Ждать";\nConsole.WriteLine(order);',
                "blank": "?",
                "rewardXp": 15,
            },
            {
                "id": "t2-task-6", "type": "single-choice",
                "title": "Арни: книга про мир за лесом",
                "npcText": "Арни шепчет: «Я нашёл книгу. Если она про море — отдать в библиотеку, если про другой материк — спрятать, иначе — оставить мне. Какое сравнение тут не пройдёт?»",
                "question": "Какое из выражений вернёт ошибку компиляции в условии else if?",
                "options": [
                    'topic == "море"',
                    'topic = "море"',
                    'topic != "море"',
                    "topic.Length > 0",
                ],
                "correctIndex": 1,
                "rewardXp": 15,
            },
            {
                "id": "t2-task-7", "type": "match-pairs",
                "title": "Пиксис: распознай сигнал",
                "npcText": "«Каждая ракета — свой приказ. Сопоставь.»",
                "pairs": [
                    {"left": "зелёная", "right": "Возвращаемся домой"},
                    {"left": "жёлтая",  "right": "Замечен обычный, готовиться"},
                    {"left": "красная", "right": "Аномальный — всем в позиции"},
                    {"left": "чёрная",  "right": "Командование, срочный сбор"},
                ],
                "rewardXp": 20,
            },
            {
                "id": "t2-task-8", "type": "code-order",
                "title": "Сигнальные ракеты — switch",
                "npcText": "«Дай мне корректный switch, по сигналу буду действовать.»",
                "description": "Расставь строки, чтобы получился корректный switch с break-ами.",
                "lines": [
                    'string signal = "красная";',
                    "switch (signal)",
                    "{",
                    '    case "зелёная":',
                    '        Console.WriteLine("Безопасно");',
                    "        break;",
                    '    case "красная":',
                    '        Console.WriteLine("Аномальный!");',
                    "        break;",
                    "    default:",
                    '        Console.WriteLine("Неизвестный сигнал");',
                    "        break;",
                    "}",
                ],
                "correctOrder": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                "rewardXp": 20,
            },
            {
                "id": "t2-task-final", "type": "find-the-bug",
                "title": "Саша делит еду",
                "npcText": "«Я делю провизию по званиям. Но что-то одна ветка съедает чужой паёк — найди.»",
                "lines": [
                    'string rank = "scout";',
                    'if (rank == "captain")',
                    "{",
                    '    Console.WriteLine("Большой паёк");',
                    "}",
                    'else if (rank == "scout")',
                    "{",
                    '    Console.WriteLine("Средний паёк");',
                    "}",
                    'else if (rank == "scout")',
                    "{",
                    '    Console.WriteLine("Двойной паёк");',
                    "}",
                    "else",
                    "{",
                    '    Console.WriteLine("Стандартный паёк");',
                    "}",
                ],
                "bugLineIndex": 9,
                "explanation": "Вторая ветка else if проверяет то же условие, что и первая — она никогда не сработает. Должно быть другое звание.",
                "rewardXp": 25,
            },
        ],
        "finalAction": {
            "id": "t2-inspire-corps",
            "title": "Вдохновить корпус",
            "cutsceneBlocks": [
                {"type": "title", "content": "Вдохновить корпус"},
                {"type": "text",  "content": "# обходит позиции одну за другой. Раздаёт собранное — флаги, перевязки, тёплый хлеб от Саши. Просто стоит рядом, ничего не говорит."},
                {"type": "text",  "content": "К рассвету корпус строится перед последней атакой. Пиксис вытаскивает фляжку и кивает #: «Дальше — наше.»"},
                {"type": "text",  "content": "Сама битва впереди — её мы оставим на потом, когда сможем писать код задачи целиком."},
            ],
        },
    },

    # ===========================================================================
    # ТЕМА 3 — ГОРОД МЕНЕСТРЕЛЕЙ (Циклы). Отсылка: Король и Шут.
    # ===========================================================================
    {
        "id": "topic-3",
        "order": 3,
        "title": "Город Менестрелей",
        "storyPage": {
            "id": "t3-story-intro",
            "title": "Бесконечная баллада",
            "blocks": [
                {"type": "title", "content": "Город Менестрелей"},
                {"type": "text",  "content": "После Стен до # доходит слух: где-то на западе песни не заканчиваются. Никогда. Городу нужна помощь."},
                {"type": "text",  "content": "# заходит за ворота — и слышит. Барабан бьёт без перерыва. Певица тянет один и тот же куплет. Скрипач застрял на одной ноте. Танцор кружится посреди площади."},
                {"type": "text",  "content": "На городе проклятие — Бесконечная Баллада. У музыки нет условия выхода. Чтобы освободить город, # должен вытащить каждого музыканта из его петли и сыграть финальный «забытый» куплет на колокольне."},
            ],
        },
        "theoryPages": [
            {
                "id": "t3-l1-while",
                "title": "while",
                "blocks": [
                    {"type": "title", "content": "Цикл while"},
                    {"type": "text",  "content": "while выполняется пока условие истинно. Удобен, когда количество итераций заранее неизвестно."},
                    {"type": "code",  "content": "int energy = 3;\n\nwhile (energy > 0)\n{\n    Console.WriteLine(\"Куплет\");\n    energy--;\n}"},
                    {"type": "text",  "content": "Если забыть менять переменную внутри — цикл будет бесконечным."},
                ],
            },
            {
                "id": "t3-l2-for",
                "title": "for",
                "blocks": [
                    {"type": "title", "content": "Цикл for"},
                    {"type": "text",  "content": "Удобен, когда заранее знаешь, сколько раз нужно повторить."},
                    {"type": "code",  "content": "for (int i = 0; i < 5; i++)\n{\n    Console.WriteLine(\"Куплет \" + i);\n}"},
                    {"type": "text",  "content": "Три блока: инициализация, условие, шаг."},
                ],
            },
            {
                "id": "t3-l3-do-while",
                "title": "do-while",
                "blocks": [
                    {"type": "title", "content": "do-while"},
                    {"type": "text",  "content": "Тело цикла выполняется хотя бы один раз — даже если условие сразу false."},
                    {"type": "code",  "content": "int audience = 0;\n\ndo\n{\n    Console.WriteLine(\"Припев\");\n}\nwhile (audience > 0);"},
                    {"type": "text",  "content": "Сравни с обычным while: там тело могло бы не выполниться ни разу."},
                ],
            },
            {
                "id": "t3-l4-break",
                "title": "break",
                "blocks": [
                    {"type": "title", "content": "break"},
                    {"type": "text",  "content": "break прерывает цикл полностью."},
                    {"type": "code",  "content": "for (int i = 0; i < 10; i++)\n{\n    if (i == 5) break;\n    Console.WriteLine(i);\n}\n// Выведет 0,1,2,3,4"},
                ],
            },
            {
                "id": "t3-l5-continue",
                "title": "continue",
                "blocks": [
                    {"type": "title", "content": "continue"},
                    {"type": "text",  "content": "continue пропускает текущую итерацию и идёт к следующей."},
                    {"type": "code",  "content": "for (int i = 0; i < 5; i++)\n{\n    if (i == 2) continue;\n    Console.WriteLine(i);\n}\n// Выведет 0,1,3,4"},
                ],
            },
            {
                "id": "t3-l6-infinite",
                "title": "Бесконечные циклы",
                "blocks": [
                    {"type": "title", "content": "while (true)"},
                    {"type": "text",  "content": "Иногда нужен цикл, который работает «всегда» — например, главный игровой цикл. Используют while (true) с выходом через break внутри."},
                    {"type": "code",  "content": "while (true)\n{\n    string input = Console.ReadLine();\n    if (input == \"стоп\") break;\n    Console.WriteLine(\"Команда: \" + input);\n}"},
                    {"type": "text",  "content": "Без break это будет настоящий бесконечный цикл — программа зависнет."},
                ],
            },
        ],
        "tasks": [
            {
                "id": "t3-task-1", "type": "single-choice",
                "title": "Барабанщик: что такое while",
                "npcText": "Барабан бьёт без остановки. «Бью, пока есть силы… а что это вообще такое?»",
                "question": "Что делает цикл while?",
                "options": [
                    "выполняет тело один раз",
                    "выполняет тело, пока условие истинно",
                    "выполняет тело заданное число раз",
                    "никогда не выполняет тело",
                ],
                "correctIndex": 1,
                "rewardXp": 10,
            },
            {
                "id": "t3-task-2", "type": "find-the-bug",
                "title": "Барабанщик: бесконечная баллада",
                "npcText": "«Цикл не отпускает! Сделай так, чтобы он мог закончиться.»",
                "lines": [
                    "while (true)",
                    "{",
                    '    Console.WriteLine("Удар!");',
                    "}",
                ],
                "bugLineIndex": 0,
                "explanation": "Цикл while (true) без break внутри — бесконечный. Должна быть проверка на условие выхода (например, if (drumsLeft == 0) break).",
                "rewardXp": 20,
            },
            {
                "id": "t3-task-3", "type": "fill-in-blank",
                "title": "Певица: спеть ровно N куплетов",
                "npcText": "«Мне сказали — ровно пять куплетов. Допиши условие.»",
                "codeTemplate": "for (int i = 0; i ___ 5; i++)\n{\n    Console.WriteLine(\"Куплет \" + i);\n}",
                "blank": "<",
                "rewardXp": 15,
            },
            {
                "id": "t3-task-4", "type": "code-order",
                "title": "Певица: пока есть силы",
                "npcText": "«Петь, пока энергия не кончится. Собери код.»",
                "description": "Расставь строки в правильном порядке — цикл while с уменьшением энергии.",
                "lines": [
                    "int energy = 3;",
                    "while (energy > 0)",
                    "{",
                    '    Console.WriteLine("Куплет");',
                    "    energy--;",
                    "}",
                ],
                "correctOrder": [0, 1, 2, 3, 4, 5],
                "rewardXp": 20,
            },
            {
                "id": "t3-task-5", "type": "fill-in-blank",
                "title": "Скрипач: пропустить фальшь",
                "npcText": "«Третий аккорд фальшивый. Пропусти его — продолжай.»",
                "codeTemplate": "for (int i = 0; i < 5; i++)\n{\n    if (i == 2) ___;\n    Console.WriteLine(\"Аккорд \" + i);\n}",
                "blank": "continue",
                "rewardXp": 15,
            },
            {
                "id": "t3-task-6", "type": "single-choice",
                "title": "Скрипач: что делает break",
                "npcText": "«Струна лопнула. Дальше играть нельзя. Что делает break?»",
                "question": "Что делает оператор break внутри цикла?",
                "options": [
                    "пропускает одну итерацию и идёт дальше",
                    "полностью прерывает цикл",
                    "перезапускает цикл сначала",
                    "выводит сообщение об ошибке",
                ],
                "correctIndex": 1,
                "rewardXp": 10,
            },
            {
                "id": "t3-task-7", "type": "match-pairs",
                "title": "Танцор: while vs do-while",
                "npcText": "«Один пируэт сделать надо точно — даже если в зале пусто. Сопоставь, что про что.»",
                "pairs": [
                    {"left": "while",      "right": "Может не выполниться ни разу"},
                    {"left": "do-while",   "right": "Выполняется хотя бы один раз"},
                    {"left": "for",        "right": "Когда знаешь число повторений"},
                    {"left": "while (true)", "right": "Когда выход — только через break"},
                ],
                "rewardXp": 20,
            },
            {
                "id": "t3-task-8", "type": "code-order",
                "title": "Танцор: финальная поза",
                "npcText": "«Прыгаю до сигнала — потом замираю. Собери код с break-ом.»",
                "description": "Расставь строки — цикл прыжков, прерываемый break по сигналу.",
                "lines": [
                    "for (int i = 0; i < 100; i++)",
                    "{",
                    "    if (signal)",
                    "    {",
                    "        break;",
                    "    }",
                    '    Console.WriteLine("Прыжок " + i);',
                    "}",
                    'Console.WriteLine("Финальная поза");',
                ],
                "correctOrder": [0, 1, 2, 3, 4, 5, 6, 7, 8],
                "rewardXp": 20,
            },
        ],
        "finalAction": {
            "id": "t3-final-verse",
            "title": "Сыграть финальный куплет",
            "cutsceneBlocks": [
                {"type": "title", "content": "Финальный куплет"},
                {"type": "text",  "content": "# поднимается на колокольню. Шесть собранных нот ложатся на каменный край — каждая помнит свою петлю."},
                {"type": "text",  "content": "Тот самый «забытый» куплет идёт сам. Барабан замолкает. Скрипка отпускает ноту. Танцор замирает."},
                {"type": "text",  "content": "Город дышит впервые за много месяцев. Один из музыкантов подходит и говорит #: «На восточной дороге — алхимики. Там тоже неладно.»"},
            ],
        },
    },

    # ===========================================================================
    # ТЕМА 4 — ГОРОД АЛХИМИКОВ (Методы + рекурсия). Отсылка: Breaking Bad.
    # ===========================================================================
    {
        "id": "topic-4",
        "order": 4,
        "title": "Город Алхимиков",
        "storyPage": {
            "id": "t4-story-intro",
            "title": "Восточная дорога",
            "blocks": [
                {"type": "title", "content": "Город Алхимиков"},
                {"type": "text",  "content": "Один из расколдованных музыкантов сказал #: «На восточной дороге слышно про алхимиков. Там тоже неладно.»"},
                {"type": "text",  "content": "В городе — открытые лавки, запах трав и кислот, шумный рынок. Алхимия легальна. Но есть один «но»: всё это под Густом — монополистом, который заставляет варить наркотическое зелье."},
                {"type": "text",  "content": "На отшибе сидит человек, который отказался. Мистер Уойд. У него есть план: собрать взрывчатку, снести штаб Густа и открыть ворота на восток. # — последний, кто ему нужен."},
            ],
        },
        "theoryPages": [
            {
                "id": "t4-l1-void",
                "title": "Что такое метод",
                "blocks": [
                    {"type": "title", "content": "Метод"},
                    {"type": "text",  "content": "Метод — именованный кусок кода, который можно вызвать. Уойд называет это «рецептом»."},
                    {"type": "code",  "content": "void Greet()\n{\n    Console.WriteLine(\"Привет!\");\n}\n\nGreet(); // вызов\nGreet(); // ещё раз"},
                    {"type": "text",  "content": "void — метод ничего не возвращает. Просто делает."},
                ],
            },
            {
                "id": "t4-l2-param",
                "title": "Параметр метода",
                "blocks": [
                    {"type": "title", "content": "Один параметр"},
                    {"type": "text",  "content": "Параметр — ингредиент рецепта. Передаётся при вызове."},
                    {"type": "code",  "content": "void Greet(string name)\n{\n    Console.WriteLine(\"Привет, \" + name);\n}\n\nGreet(\"Уойд\");\nGreet(\"Джон\");"},
                ],
            },
            {
                "id": "t4-l3-params",
                "title": "Несколько параметров",
                "blocks": [
                    {"type": "title", "content": "Много параметров"},
                    {"type": "text",  "content": "У метода может быть сколько угодно параметров. Порядок при вызове должен совпадать."},
                    {"type": "code",  "content": "void Mix(string a, string b)\n{\n    Console.WriteLine(\"Смешиваю \" + a + \" и \" + b);\n}\n\nMix(\"кислота\", \"соль\");"},
                ],
            },
            {
                "id": "t4-l4-return",
                "title": "return",
                "blocks": [
                    {"type": "title", "content": "Возврат значения"},
                    {"type": "text",  "content": "Если метод что-то возвращает — вместо void пишем тип возврата, и используем return."},
                    {"type": "code",  "content": "int Add(int a, int b)\n{\n    return a + b;\n}\n\nint result = Add(3, 5); // 8"},
                    {"type": "text",  "content": "После return метод заканчивает работу. Всё, что ниже — не выполнится."},
                ],
            },
            {
                "id": "t4-l5-compose",
                "title": "Метод из метода",
                "blocks": [
                    {"type": "title", "content": "Композиция"},
                    {"type": "text",  "content": "Один метод может вызывать другой. Так из маленьких рецептов собирают большие."},
                    {"type": "code",  "content": "string MakeAcid()     { return \"кислота\"; }\nstring MakeOxidizer() { return \"окислитель\"; }\n\nstring MakeBomb()\n{\n    string a = MakeAcid();\n    string b = MakeOxidizer();\n    return a + \" + \" + b;\n}"},
                ],
            },
            {
                "id": "t4-l6-recursion",
                "title": "Рекурсия",
                "blocks": [
                    {"type": "title", "content": "Рекурсия"},
                    {"type": "text",  "content": "Метод может вызывать сам себя. Это рекурсия. Обязательно нужен базовый случай — иначе бесконечный вызов."},
                    {"type": "code",  "content": "int Countdown(int n)\n{\n    if (n == 0) return 0;        // базовый случай\n    Console.WriteLine(n);\n    return Countdown(n - 1);     // рекурсия\n}"},
                    {"type": "text",  "content": "Без if (n == 0) return 0 — программа упадёт со StackOverflow."},
                ],
            },
        ],
        "tasks": [
            {
                "id": "t4-task-1", "type": "single-choice",
                "title": "Знакомство с Уойдом",
                "npcText": "Уойд кладёт на стол маленькую горсть сухого порошка. «Сначала проверим. Что такое метод?»",
                "question": "Что такое метод в C#?",
                "options": [
                    "команда вывода в консоль",
                    "именованный кусок кода, который можно вызвать",
                    "название переменной",
                    "тип данных",
                ],
                "correctIndex": 1,
                "rewardXp": 10,
            },
            {
                "id": "t4-task-2", "type": "find-the-bug",
                "title": "Бочка-мем",
                "npcText": "Джон тянет за верёвку. «Тащу бочку!» Уойд из угла: «Джон. У бочки есть колёса.»",
                "lines": [
                    "void DragBarrel(int distance)",
                    "{",
                    '    Console.WriteLine("Тащу бочку на " + distance);',
                    "}",
                    "",
                    "DragBarrel(50);",
                ],
                "bugLineIndex": 5,
                "explanation": "Бочку нужно катить, а не тащить. Должен быть вызов RollBarrel(50) — соответствующего метода (или сам метод нужно переименовать).",
                "rewardXp": 25,
            },
            {
                "id": "t4-task-3", "type": "match-pairs",
                "title": "Уойд: рецепты и ингредиенты",
                "npcText": "«Каждому рецепту — свой набор. Сопоставь.»",
                "pairs": [
                    {"left": "Brew(water, herb)",       "right": "(жидкость, ингредиент)"},
                    {"left": "Mix(reagent1, reagent2)", "right": "(два реагента)"},
                    {"left": "Refine(crude, level)",    "right": "(сырьё, уровень очистки)"},
                    {"left": "Bind(base, modifier)",    "right": "(основа, модификатор)"},
                ],
                "rewardXp": 20,
            },
            {
                "id": "t4-task-4", "type": "single-choice",
                "title": "I am the danger",
                "npcText": "Джон тихо: «Тебе не страшно идти против Густа?» Уойд показывает #: «Что вернёт этот метод?»",
                "question": "Что вернёт метод?\n\nstring WhoIsTheDanger()\n{\n    return \"я\";\n}",
                "options": ['"Густ"', '"опасность"', '"я"', "null"],
                "correctIndex": 2,
                "rewardXp": 15,
            },
            {
                "id": "t4-task-5", "type": "code-order",
                "title": "Сборка взрывчатки",
                "npcText": "«Соберём её по частям. Сначала кислота, потом окислитель, потом смесь.»",
                "description": "Расставь строки внутри метода MakeBomb так, чтобы он сначала получил кислоту, потом окислитель, и вывел готовую смесь.",
                "lines": [
                    "string acid = MakeAcid();",
                    "string oxidizer = MakeOxidizer();",
                    'string bomb = acid + " + " + oxidizer;',
                    'Console.WriteLine("Готова смесь: " + bomb);',
                ],
                "correctOrder": [0, 1, 2, 3],
                "rewardXp": 20,
            },
            {
                "id": "t4-task-6", "type": "find-the-bug",
                "title": "Финальная очистка",
                "npcText": "«Последний рецепт. Проверь — он зовёт сам себя.» Уойд протягивает листок.",
                "lines": [
                    "double Purify(double impurity)",
                    "{",
                    "    return Purify(impurity / 2);",
                    "}",
                ],
                "bugLineIndex": 2,
                "explanation": "Нет базового случая. Метод вызывает сам себя без условия выхода — бесконечная рекурсия. Нужно добавить: if (impurity < 0.01) return impurity;",
                "rewardXp": 30,
            },
        ],
        "finalAction": {
            "id": "t4-blow-up-gust",
            "title": "Взорвать штаб Густа",
            "cutsceneBlocks": [
                {"type": "title", "content": "Взрыв"},
                {"type": "text",  "content": "# и Уойд закладывают собранные реагенты у штаба. Уойд проверяет ещё раз — Purify, базовый случай на месте. Можно."},
                {"type": "text",  "content": "Взрыв. Поднимается пыль, рушится фасад. Густ — больше не монополист."},
                {"type": "text",  "content": "Уойд кивает #: «Теперь можно. Дорога на восток открыта.» Над городом проступает столица."},
            ],
        },
    },

    # ===========================================================================
    # ТЕМА 5 — СТОЛИЦА (Массивы). Атмосфера: народное сопротивление.
    # ===========================================================================
    {
        "id": "topic-5",
        "order": 5,
        "title": "Столица",
        "storyPage": {
            "id": "t5-story-intro",
            "title": "Подполье",
            "blocks": [
                {"type": "title", "content": "Столица"},
                {"type": "text",  "content": "Ворота столицы серые, забитые, под флагами Null. # ещё не успевает выдохнуть — из тени выходит человек."},
                {"type": "text",  "content": "«Мы знали, что ты придёшь.» Молодой, спокойный. Уводит в подвал, где горит одна свеча. Его зовут Клаус."},
                {"type": "text",  "content": "Клаус объясняет коротко: Null захватил трон год назад. Принцесса C — у него во дворце. Он питается её жизненной силой, чтобы жить вечно. Из-за этого # был год в коме."},
                {"type": "text",  "content": "В одиночку штурм бессмыслен. Нужен отряд. # пройдёт по столице — каждый, кого получится поднять, это ещё один в строю."},
            ],
        },
        "theoryPages": [
            {
                "id": "t5-l1-concept",
                "title": "Что такое массив",
                "blocks": [
                    {"type": "title", "content": "Массив"},
                    {"type": "text",  "content": "Массив — это коллекция значений одного типа под одним именем. У каждого элемента есть позиция (индекс). Нумерация с нуля."},
                    {"type": "code",  "content": 'string[] rebels = { "Грета", "Отто", "Ганс", "Вернер" };'},
                    {"type": "text",  "content": "В подполье это «список имён в строю»."},
                ],
            },
            {
                "id": "t5-l2-declare",
                "title": "Объявление и инициализация",
                "blocks": [
                    {"type": "title", "content": "Два способа объявить"},
                    {"type": "code",  "content": '// 1. Сразу со значениями\nstring[] rebels = { "Грета", "Отто", "Ганс" };\n\n// 2. Пустой массив фиксированного размера\nstring[] empty = new string[5];'},
                    {"type": "text",  "content": "Во втором случае все элементы по умолчанию: для строк — null, для чисел — 0."},
                ],
            },
            {
                "id": "t5-l3-index",
                "title": "Доступ по индексу",
                "blocks": [
                    {"type": "title", "content": "Индекс"},
                    {"type": "text",  "content": "Чтобы получить элемент — пиши имя[индекс]. Первый элемент — индекс 0."},
                    {"type": "code",  "content": 'string[] rebels = { "Грета", "Отто", "Ганс", "Вернер" };\n\nConsole.WriteLine(rebels[0]); // Грета\nConsole.WriteLine(rebels[2]); // Ганс'},
                    {"type": "text",  "content": "Выход за границу (rebels[10]) — runtime-ошибка IndexOutOfRangeException."},
                ],
            },
            {
                "id": "t5-l4-length",
                "title": "Length",
                "blocks": [
                    {"type": "title", "content": "Сколько элементов"},
                    {"type": "text",  "content": "У каждого массива есть свойство Length — количество элементов."},
                    {"type": "code",  "content": 'string[] rebels = { "Грета", "Отто", "Ганс" };\nConsole.WriteLine(rebels.Length); // 3'},
                ],
            },
            {
                "id": "t5-l5-modify",
                "title": "Изменение элемента",
                "blocks": [
                    {"type": "title", "content": "Поменять элемент"},
                    {"type": "text",  "content": "Размер массива неизменен, но содержимое менять можно."},
                    {"type": "code",  "content": 'string[] rebels = { "Грета", "Отто", "Доносчик", "Вернер" };\nrebels[2] = "[пусто]";\nConsole.WriteLine(rebels[2]); // [пусто]'},
                ],
            },
            {
                "id": "t5-l6-for",
                "title": "Обход через for",
                "blocks": [
                    {"type": "title", "content": "for + индекс"},
                    {"type": "text",  "content": "Когда нужен сам индекс — используй for."},
                    {"type": "code",  "content": 'string[] rebels = { "Грета", "Отто", "Ганс" };\n\nfor (int i = 0; i < rebels.Length; i++)\n{\n    Console.WriteLine(rebels[i]);\n}'},
                    {"type": "text",  "content": "Условие i < rebels.Length — не путать с <=! С <= выйдешь за границу."},
                ],
            },
            {
                "id": "t5-l7-foreach",
                "title": "Обход через foreach",
                "blocks": [
                    {"type": "title", "content": "foreach"},
                    {"type": "text",  "content": "Когда индекс не нужен — foreach короче и понятнее."},
                    {"type": "code",  "content": 'string[] rebels = { "Грета", "Отто", "Ганс" };\n\nforeach (string name in rebels)\n{\n    Console.WriteLine(name);\n}'},
                    {"type": "text",  "content": "В foreach нельзя изменить элемент массива через переменную цикла — для этого нужен for."},
                ],
            },
            {
                "id": "t5-l8-search",
                "title": "Поиск в массиве",
                "blocks": [
                    {"type": "title", "content": "Поиск через цикл"},
                    {"type": "text",  "content": "Чтобы проверить, есть ли элемент в массиве — пробегаем циклом и сравниваем."},
                    {"type": "code",  "content": 'string[] rebels = { "Грета", "Отто", "Ганс" };\nbool found = false;\n\nfor (int i = 0; i < rebels.Length; i++)\n{\n    if (rebels[i] == "Отто")\n    {\n        found = true;\n        break;\n    }\n}\n\nConsole.WriteLine(found); // True'},
                ],
            },
        ],
        "tasks": [
            {
                "id": "t5-task-1", "type": "single-choice",
                "title": "Клаус: что такое массив",
                "npcText": "Клаус кладёт на стол старый листок со списком имён. «Понимаешь, что это?»",
                "question": "Что такое массив?",
                "options": [
                    "именованная коллекция значений одного типа",
                    "список значений разных типов",
                    "команда вывода",
                    "способ объявления переменной",
                ],
                "correctIndex": 0,
                "rewardXp": 10,
            },
            {
                "id": "t5-task-2", "type": "code-order",
                "title": "Клаус: объявить отряд",
                "npcText": "«Запиши четверых, кто готов прямо сейчас.»",
                "description": "Расставь строки в правильном порядке.",
                "lines": [
                    'string[] rebels = { "Грета", "Отто", "Ганс", "Вернер" };',
                    'Console.WriteLine("Отряд собран: " + rebels.Length);',
                ],
                "correctOrder": [0, 1],
                "rewardXp": 15,
            },
            {
                "id": "t5-task-3", "type": "code-order",
                "title": "Грета: третий — доносчик",
                "npcText": "Грета шепчет: «Третий в твоём списке — стукач. Покажи его имя.»",
                "description": "Собери код, который выводит имя третьего элемента массива (через индекс 2).",
                "lines": [
                    "string traitor = rebels[2];",
                    'Console.WriteLine("Доносчик: " + traitor);',
                ],
                "correctOrder": [0, 1],
                "rewardXp": 15,
            },
            {
                "id": "t5-task-4", "type": "fill-in-blank",
                "title": "Отто: вычеркнуть доносчика",
                "npcText": "Отто молча подходит, забирает листок. «Имя — на ноль.»",
                "codeTemplate": 'rebels[___] = "[пусто]";',
                "blank": "2",
                "rewardXp": 15,
            },
            {
                "id": "t5-task-5", "type": "fill-in-blank",
                "title": "Ганс: сколько нас осталось",
                "npcText": "Ганс считает на пальцах. «А сколько в массиве сейчас, включая [пусто]?»",
                "codeTemplate": "int count = rebels.___;\nConsole.WriteLine(\"В строю: \" + count);",
                "blank": "Length",
                "rewardXp": 10,
            },
            {
                "id": "t5-task-6", "type": "fill-in-blank",
                "title": "Вернер: перекличка строя",
                "npcText": "Вернер строит всех. «Поимённо — каждого.»",
                "codeTemplate": "for (int i = 0; i < ___; i++)\n{\n    Console.WriteLine(rebels[i]);\n}",
                "blank": "rebels.Length",
                "rewardXp": 15,
            },
            {
                "id": "t5-task-7", "type": "code-order",
                "title": "Ганс: кто готов к бою",
                "npcText": "«У каждого — массив readiness, true/false. Посчитай, сколько true.»",
                "description": "Собери цикл for, который считает количество true в массиве readiness.",
                "lines": [
                    "int ready = 0;",
                    "for (int i = 0; i < readiness.Length; i++)",
                    "{",
                    "    if (readiness[i]) ready++;",
                    "}",
                    'Console.WriteLine("Готовы: " + ready);',
                ],
                "correctOrder": [0, 1, 2, 3, 4, 5],
                "rewardXp": 20,
            },
            {
                "id": "t5-task-8", "type": "fill-in-blank",
                "title": "Хельга: раздать снаряжение",
                "npcText": "Хельга по очереди подходит к каждому. «Хлеб и оружие — всем. Допиши.»",
                "codeTemplate": "foreach (string rebel in ___)\n{\n    Equip(rebel);\n    GiveBread(rebel);\n}",
                "blank": "rebels",
                "rewardXp": 20,
            },
            {
                "id": "t5-task-9", "type": "single-choice",
                "title": "Фриц: список схваченных",
                "npcText": "Фриц приносит листок. «Список задержанных. Если там есть кто-то из верхушки — нас сдают.»",
                "question": 'Какой из вариантов корректно проверяет, есть ли имя "Клаус" в массиве captured?',
                "options": [
                    'bool found = false;\nfor (int i = 0; i < captured.Length; i++) {\n    if (captured[i] == "Клаус") { found = true; break; }\n}',
                    'bool found = captured == "Клаус";',
                    'bool found = captured.Length == "Клаус";',
                    'bool found = "Клаус" in captured;',
                ],
                "correctIndex": 0,
                "rewardXp": 20,
            },
            {
                "id": "t5-task-10", "type": "find-the-bug",
                "title": "Клаус: финальная сверка",
                "npcText": "«Перед штурмом — проверь последний раз. Тут где-то выходит за край.»",
                "lines": [
                    "for (int i = 0; i <= rebels.Length; i++)",
                    "{",
                    '    Console.WriteLine("В строю: " + rebels[i]);',
                    "}",
                ],
                "bugLineIndex": 0,
                "explanation": "Условие i <= rebels.Length должно быть i < rebels.Length. С <= индекс на последней итерации выйдет за границу массива.",
                "rewardXp": 30,
            },
        ],
        "finalAction": {
            "id": "t5-storm",
            "title": "Штурм дворца",
            "cutsceneBlocks": [
                {"type": "title", "content": "Штурм"},
                {"type": "text",  "content": "Эта сцена будет реализована позже — в текущей версии Тема 5 проходится как набор заданий, без финальной кнопки."},
                {"type": "text",  "content": "Запланировано: штурм дворца Null, спасение принцессы C, возврат памяти # — в виде катсцены или code-write задачи, которая поднимает массив повстанцев в атаку."},
            ],
        },
    },
]
